export const LANGS = {
  EN: {
    greeting: "Hello! Welcome to MHFA Connect. How can we support you today?",
    privacy: "100% Anonymous & Secure",
    h1: "Mental Health First Aid",
    p: "Get immediate triage, access regional helplines, or speak with trained peers.",
    qa1: "AI Triage Chat",
    qa1s: "Instant anonymous guidance",
    qa2: "Self-Help Modules",
    qa2s: "Downloadable guides",
    qa3: "Support Directory",
    qa3s: "Campus & national helplines",
    qa4: "Peer Support",
    qa4s: "Talk to trained peers",
    peerTitle: "Peer Support Counselors",
    peerSub: "Connect confidentially with a student peer supporter.",
    startPeerChat: "Start Chat",
    selfHelpTitle: "Self-Help Resources",
    selfHelpSub: "Offline-accessible guides for stress and mental well-being.",
    downloadBtn: "Download TXT",
    findSupportTitle: "Helplines & Resources",
    findSupportSub: "Verified local and national emergency contacts.",
    settingsTitle: "Settings & Privacy",
    privacySec: "Security",
    pinLock: "Quick Exit PIN",
    pinSub: "Lock or exit session rapidly for privacy",
    setPinBtn: "Set PIN",
    dangerZone: "Session Management",
    logoutBtn: "Log Out & Clear Session",
    pinModalTitle: "Quick Exit PIN",
    pinModalSub: "Enter a 4-digit security PIN",
    cancel: "Cancel",
    savePin: "Save PIN"
  },
  SH: {
    greeting: "Lumela! Re u amohela ho MHFA Connect. Re ka u meletsa joang kajeno?",
    privacy: "100% Ea Lekunutu le Ts'ireletseho",
    h1: "Thuso ea Pele ea Bophelo ba Kelello",
    p: "Fumana thuso kapele, fihlela linomboro tsa tšohanyetso, kapa bua le lithaka.",
    qa1: "Puisano ea AI",
    qa1s: "Tlhahiso-leseling ea kapele",
    qa2: "Lisebelisoa tsa ho Ithusang",
    qa2s: "Litaelo tse ka jarollang",
    qa3: "Lits'ebeletso tsa Thuso",
    qa3s: "Linomboro tsa khamphase le naha",
    qa4: "Tšehetso ea Lithaka",
    qa4s: "Bua le baithuti ba koetlisitsoeng",
    peerTitle: "Baeletsi ba Lithaka",
    peerSub: "Ikopanye le moithuti oa thaka ka lekunutu.",
    startPeerChat: "Qala Puisano",
    selfHelpTitle: "Lisebelisoa tsa ho Ithuta",
    selfHelpSub: "Litaelo tsa ho laola ho satalala ha kelello.",
    downloadBtn: "Jarolla TXT",
    findSupportTitle: "Linomboro tsa Thuso",
    findSupportSub: "Mabitso a tšohanyetso a lehae le naha.",
    settingsTitle: "Lisebelisoa le Lekunutu",
    privacySec: "Ts'ireletso",
    pinLock: "PIN ea ho Tsoa Kapele",
    pinSub: "Koala lenaneo kapele bakeng sa lekunutu",
    setPinBtn: "Seta PIN",
    dangerZone: "Tsamaiso ea Lenaneo",
    logoutBtn: "Tsoa le ho Hlakola",
    pinModalTitle: "PIN ea ho Tsoa",
    pinModalSub: "Kenya PIN ea linomboro tse 4",
    cancel: "Hlakola",
    savePin: "Boloka PIN"
  },
  SW: {
    greeting: "Jambo! Karibu MHFA Connect. Tunawezaje kukusaidia leo?",
    privacy: "100% Sio ya Kutambulika na Salama",
    h1: "Huduma ya Kwanza ya Afya ya Akili",
    p: "Pata msaada wa haraka, fikia nambari za dharura, au zungumza na wenzako.",
    qa1: "Soga ya AI",
    qa1s: "Mwongozo wa papo hapo",
    qa2: "Rasilimali za Kujisaidia",
    qa2s: "Miongozo inayopakulika",
    qa3: "Orodha ya Msaada",
    qa3s: "Nambari za chuo na kitaifa",
    qa4: "Msaada wa Wenzangu",
    qa4s: "Zungumza na wanafunzi wenzako",
    peerTitle: "Washauri Wenzako",
    peerSub: "Ungana kwa siri na mwanafunzi mwenzako.",
    startPeerChat: "Anza Soga",
    selfHelpTitle: "Rasilimali za Kujisaidia",
    selfHelpSub: "Miongozo ya kukabiliana na msongo wa mawazo.",
    downloadBtn: "Pakua TXT",
    findSupportTitle: "Nambari za Msaada",
    findSupportSub: "Anwani za dharura za ndani na kitaifa.",
    settingsTitle: "Mipangilio na Faragha",
    privacySec: "Usalama",
    pinLock: "PIN ya Kuondoka Haraka",
    pinSub: "Funga au ondoka haraka kwa usalama",
    setPinBtn: "Weka PIN",
    dangerZone: "Usimamizi wa Kipindi",
    logoutBtn: "Ondoka na Futa Data",
    pinModalTitle: "PIN ya Kuondoka",
    pinModalSub: "Andika PIN ya tarakimu 4",
    cancel: "Ghairi",
    savePin: "Hifadhi PIN"
  },
  ZU: {
    greeting: "Sawubona! Siyakwamukela ku-MHFA Connect. Singakusiza kanjani namhlanje?",
    privacy: "100% Eyimfihlo Nokuphepha",
    h1: "Usizo Lokuqala Lwezempilo Yengqondo",
    p: "Thola usizo olusheshayo, finyelela kubuchwepheshe besimo esiphuthumayo.",
    qa1: "Ingxoxo ye-AI",
    qa1s: "Isikhokelo sosizo esisheshayo",
    qa2: "Izinsiza Zokuzisiza",
    qa2s: "Izihlahlandlela ezingalandwa",
    qa3: "Inkomba Yosizo",
    qa3s: "Inombolo zasenyuvesi ne zezwe",
    qa4: "Ukuphasisa Kontanga",
    qa4s: "Xoxa nontanga baqeqeshiwe",
    peerTitle: "Abeluleki Kontanga",
    peerSub: "Xhumana nomfundi ngendlela eyimfihlo.",
    startPeerChat: "Qala Ingxoxo",
    selfHelpTitle: "Izinsiza Zokuzisiza",
    selfHelpSub: "Izihlahlandlela zokulawula ingqondo nesineke.",
    downloadBtn: "Landa i-TXT",
    findSupportTitle: "Izincwadi Zosizo",
    findSupportSub: "Amathuluzi ashesha kakhulu asezweni.",
    settingsTitle: "Izilungiselelo Nemfihlo",
    privacySec: "Ukuphepha",
    pinLock: "I-PIN Yokuphuma Ngokushesha",
    pinSub: "Vala iseshini ngokushesha ukuze uvikeleke",
    setPinBtn: "Setha i-PIN",
    dangerZone: "Ukuphathwa Kweseshini",
    logoutBtn: "Phuma bese Uscipha Yonke Imininingwane",
    pinModalTitle: "I-PIN Yokuphuma",
    pinModalSub: "Faka i-PIN enamadijithi angu-4",
    cancel: "Khansela",
    savePin: "Gcina i-PIN"
  },
  XH: {
    greeting: "Molo! Wamkelekile kwi-MHFA Connect. Singakunceda njani namhlanje?",
    privacy: "100% Eyimfihlo Khuselekileyo",
    h1: "Uncedo Lokuqala Lwempilo Yengqondo",
    p: "Fumana uncedo nangoko, fikelela kwiinombolo zongxamiseko.",
    qa1: "Iyncoko ye-AI",
    qa1s: "Isikhokelo esingaphiwanga ligama",
    qa2: "Izixhobo Zokuzinceda",
    qa2s: "Izikhokelo ezinokukhutshelwa",
    qa3: "Abalawuli Boncedo",
    qa3s: "Iinombolo zekhampasi nezelizwe",
    qa4: "Inkxaso Yontanga",
    qa4s: "Thatha inxaxheba nabafundi abaqeqesho",
    peerTitle: "Abaluleki BONTANGA",
    peerSub: "Qhagamshelana ngobuhlobo nomfundi ontanga.",
    startPeerChat: "Qalisa Ingxoxo",
    selfHelpTitle: "Izixhobo Zokuzinceda",
    selfHelpSub: "Izikhokelo zokulawula uxinzelelo lwasengqondweni.",
    downloadBtn: "Khuphela i-TXT",
    findSupportTitle: "Iinombolo Zoncedo",
    findSupportSub: "Iifowuni zongxamiseko zangaphakathi nezelizwe.",
    settingsTitle: "Izilungiselelo Neemfihlo",
    privacySec: "Khuselekileyo",
    pinLock: "I-PIN Yokuphuma Ngokukhawuleza",
    pinSub: "Vala iseshoni ngoko nangoko",
    setPinBtn: "Seta i-PIN",
    dangerZone: "Ulawulo Lweseshoni",
    logoutBtn: "Phuma Susa Yonke Data",
    pinModalTitle: "I-PIN Yokuphuma",
    pinModalSub: "Faka i-PIN enamanani ama-4",
    cancel: "Rhoxisa",
    savePin: "Gcina i-PIN"
  },
  AF: {
    greeting: "Hallo! Welkom by MHFA Connect. Hoe kan ons jou vandag ondersteun?",
    privacy: "100% Anoniem & Veilig",
    h1: "Geestesgesondheid Eerstehulp",
    p: "Kry onmiddellike leiding, toegang tot noodlyne, of praat met opgeleide porture.",
    qa1: "Kletsbot-Ondersteuning",
    qa1s: "Onmiddellike anonieme leiding",
    qa2: "Selfhelp-Modules",
    qa2s: "Aflaaibare gidse",
    qa3: "Ondersteuningsgids",
    qa3s: "Kampus- en nasionale hulplyne",
    qa4: "Portuurondersteuning",
    qa4s: "Praat met opgeleide studente",
    peerTitle: "Portuurraadgewers",
    peerSub: "Verbind vertroulik met 'n mede-student.",
    startPeerChat: "Begin Klets",
    selfHelpTitle: "Selfhelp-Hulpbronne",
    selfHelpSub: "Gidse vir die bestuur van spanning en welstand.",
    downloadBtn: "Laai TXT Af",
    findSupportTitle: "Noodlyne & Hulpbronne",
    findSupportSub: "Gekontroleerde plaaslike en nasionale kontakte.",
    settingsTitle: "Instellings & Privaatheid",
    privacySec: "Sekuriteit",
    pinLock: "Vinnige Uitgang PIN",
    pinSub: "Sluit of verlaat sessie vinnig vir privaatheid",
    setPinBtn: "Stel PIN In",
    dangerZone: "Sessiebestuur",
    logoutBtn: "Meld Uit & Vee Data Skoon",
    pinModalTitle: "Vinnige Uitgang PIN",
    pinModalSub: "Voer 'n 4-syfer PIN in",
    cancel: "Kanselleer",
    savePin: "Stoor PIN"
  }
};

export const SELF_HELP_MODULES = [
  {
    id: 'm1',
    title: 'Managing Exam Anxiety',
    desc: 'Practical grounding techniques and breathing exercises for study stress.',
    type: 'Guide',
    size: '12 KB',
    content: 'EXAM ANXIETY GUIDE:\n1. Box Breathing: Inhale 4s, Hold 4s, Exhale 4s, Hold 4s.\n2. Grounding: Name 5 things you see, 4 you feel, 3 you hear, 2 you smell, 1 you taste.'
  },
  {
    id: 'm2',
    title: 'Depression & Low Mood First-Aid',
    desc: 'Understanding behavioral activation and daily self-compassion steps.',
    type: 'Guide',
    size: '15 KB',
    content: 'LOW MOOD FIRST-AID:\n1. Small Steps: Break tasks into micro-actions.\n2. Reach Out: You do not have to carry this alone.'
  }
];

export const PEER_COUNSELLORS = [
  {
    id: 'p1',
    alias: 'Peer Helper Kila',
    specialty: 'Academic Stress & Burnout',
    status: 'Available',
    rating: '★ 4.9'
  },
  {
    id: 'p2',
    alias: 'Peer Helper Thabo',
    specialty: 'Anxiety & Adjustment Support',
    status: 'Busy',
    rating: '★ 4.8'
  }
];

export const SUPPORT_DIRECTORY = [
  {
    id: 's1',
    title: 'National Emergency Crisis Helpline',
    badge: '24/7 Crisis',
    badgeClass: 'crisis',
    desc: 'Toll-free confidential support line for immediate mental health support.',
    contact: '📞 8002 2000 / 0800 212 121',
    hours: '🕒 24 Hours / 7 Days a week'
  },
  {
    id: 's2',
    title: 'Campus Wellness & Counseling Unit',
    badge: 'Campus',
    badgeClass: 'campus',
    desc: 'In-person professional counseling sessions for registered students.',
    contact: '📍 Student Center, 2nd Floor',
    hours: '🕒 Mon-Fri: 8:00 AM - 4:30 PM'
  }
];